Output example.mp4

Set Width 1280
Set Height 720
Set Zoom 1
Set Framerate 30
Set Sound true

# Frame the page on a blue background, with a padding mat around it.
Set Padding 34
Set BorderRadius 13
Set MarginFill "#813EDC"

Set Theme dark
Goto https://continuouscoordination.org/
Sleep 1s
Scroll Down 500

Hover "body > main > section > ul > li:nth-child(1) > a > h2"
Sleep 250ms
Click "body > main > section > ul > li:nth-child(1) > a > h2"
Sleep 1s
Scroll Down 500
Sleep 1s
Scroll Up 500
